# Site settings
title: Ss's Anthology
email: sansui_z@126.com
description: A young man, thinking all the time
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/wenji" # the subpath of your site, e.g. /blog/
url: "https://buyivi.xyz" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username:  Sansuiz
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# use rouge locally, pygments in Github
# highlighter: pygments
# highlighter: rouge
# highlighter: false

timezone: TIMEZONE